Text Analytics I HWS 22/23

# Home Assignment 1 (35 pts)



Submit your solution via Ilias until 23.59pm on Tuesday, October 4th. Late submissions are accepted until 10:15am on the following day (start of the exercise), with 1/4 of the total possible points deducted from the score.

Submit your solutions in teams of 3-4 students. Unless explicitly agreed otherwise in advance, **submissions from teams with more or less members will NOT be graded**.
List all members of the team with their student ID and full name in the cell below, and submit only one notebook per team. Only submit a notebook, do not submit the dataset(s) you used or image files that you have created - these have to be created from your notebook. Also, do NOT compress/zip your submission!

Cite ALL your sources for coding this home assignment. In case of plagiarism (copying solutions from other teams or from the internet) ALL team members will be expelled from the course without warning.

#### General guidelines:
* Make sure that your code is executable, any task for which the code does not directly run on our machine will be graded with 0 points.
* Use only packages that are automatically installed along with Anaconda, plus some additional packages that have been introduced in the context of this class.
* Ensure that the notebook does not rely on the current notebook or system state!
  * Use `Kernel --> Restart & Run All` to see if you are using any definitions, variables etc. that 
    are not in scope anymore.
  * Do not rename any of the datasets you use, and load it from the same directory that your ipynb-notebook is located in, i.e., your working directory.
* Make sure you clean up your code before submission, e.g., properly align your code, and delete every line of code that you do not need anymore, even if you may have experimented with it. Minimize usage of global variables. Do not reuse variable names multiple times!
* Ensure your code/notebook terminates in reasonable time.
* Feel free to use comments in the code. While we do not require them to get full marks, they may help us in case your code has minor errors.
* For questions that require a textual answer, please do not write the answer as a comment in a code cell, but in a Markdown cell below the code. Always remember to provide sufficient justification for all answers.
* You may create as many additional cells as you want, just make sure that the solutions to the individual tasks can be found near the corresponding assignment.
* If you have any general question regarding the understanding of some task, do not hesitate to post in the student forum in Ilias, so we can clear up such questions for all students in the course.

In [321]:
# credentials of all team members
team_members = [
    {
        'first_name': 'Pavani',
        'last_name': 'Rajula',
        'student_id': 1870208
    },
    {
        'first_name': 'Yves',
        'last_name': 'Staudenmaier',
        'student_id': 1754294
    },
    {
        'first_name': 'Zeynep',
        'last_name': 'Eroglu',
        'student_id': 1834472
    },
    {
        'first_name': 'Priyanka',
        'last_name': 'Roy',
        'student_id': 1933097
    }
]

In [3]:
from typing import List, Union, Dict, Set, Tuple
import numpy as np
from numpy.typing import NDArray

### Task 1: Regular expressions (9 pts)
In this task you are asked to create regular expressions that meet the specified conditions. Please use the ``re`` package for the following subtasks.

In [23]:
# import the re package 
import re

__a)__ Write a regular expression that returns all integer numbers from a text that are surrounded by whitespaces. __(1 pt)__

In [24]:
# your code here
text = ' 0000 test 1234 hey h3110 2029 w0r1d 12 1234 1200 123, 456 0002 hello 3245 12345 2019 end.'
re.findall(r' (\d+) ', text)
# re.findall(r'\b\d+\b', text)

['0000', '1234', '2029', '12', '1200', '456', '3245', '2019']

__b)__ Write a regular expression that returns all valid years that are surrounded by whitespaces in a text. A valid year is a 4 digit number in the range from 0000 to 2022. __(2 pts)__

In [18]:
# your code here
re.findall(r' ([0-1][0-9]{3}|20[0-1][0-9]|202[0-2]) ', text)

['0000', '1234', '1234', '0002', '2019']

__c)__ Write a regular expression that returns all dates in the format YYYY-MM-DD or YYYY/MM/DD from a given text. Make sure that YYYY is a valid year (see task __b)__), MM is a valid month (1 to 12) and DD is a valid day (1 to 31).
There is no need to make sure that e.g. XXXX-02-31 does not exist.  __(2 pts)__

In [24]:
# your code here
text = '2022-09-31 2022-08-31 does not exist and also 1998/02/31'
re.findall(r'([01][0-9]{3}|20[0-1][0-9]|202[0-2])[- /](0[1-9]|1[1-2])[- /]([0-2][0-9]|3[0-1])', text)
# re.findall(r'\b\d{4}-\d\d?-\d\d?\b', text)

[('2022', '09', '31'), ('2022', '08', '31'), ('1998', '02', '31')]

__d)__ Assume you are given a list ``l`` of strings like the one below. Using regular expressions, return a list that contains all elements from ``l`` that don't contain both, the letter ``a`` and ``e`` and store the result in a variable ``l_filtered``.  __(2 pts)__

__Example:__ _given the list_  

``l = ["apple", "cucumber", "tomato", "zucchini", "pumpkin", "pear", "raspberry", "blueberry"]``  

_you should return_  

``l_filtered = ['cucumber', 'tomato', 'zucchini', 'pumpkin', 'blueberry']``.

In [43]:
# example list
l = ["apple", "cucumber", "tomato", "zucchini", "pumpkin", "pear", "raspberry", "blueberry"]

In [47]:
# your code here
l_filtered = [word for word in l if not re.match(r'(?=.*a)(?=.*e).*$', word)]
l_filtered 

['cucumber', 'tomato', 'zucchini', 'pumpkin', 'blueberry']

__e)__ For the given string ``s`` with 4 lines, change the _whole_ word ``pot`` (i.e. ``pottery`` should not be changed) to ``1234`` only if it is at the start of a line.  __(2 pts)__

In [329]:
s = '''\
pottery clot pot 
pot dot plot hot
spot rot pot got
not shot forgot'''
s

'pottery clot pot \npot dot plot hot\nspot rot pot got\nnot shot forgot'

In [330]:
# your code here
s = '\n'.join([re.compile(r'^pot ').sub('1234 ', sent, 1) for sent in s.split('\n') ])
s

'pottery clot pot \n1234 dot plot hot\nspot rot pot got\nnot shot forgot'

### Task 2: Finding the most similar word (18 pts)
The goal of this task is, given a corpus, to find the most similar word for a provided word. As an example we will consider the King James Bible that is is included in the ``gutenberg`` corpus and we are looking to find the word that is most similar to ``god``. We consider two words similar if they appear in the same word context.

__a) Cleaning the input (3 pts)__

Write a function that, given a list of tokens, returns a list of tokens that we consider valid for our task. 

An *invalid* token is a token that 
- is a punctuation mark (consider `string.punctuation`).
- is entirely numeric digits (e.g. `"123"`)
- optionally, if `remove_stopwords=True` then stopwords in the English language are also not considered valid tokens (use nltk's stopwords)

Use the function signature specified in the cell below.

In [1]:
from curses.ascii import isdigit
import nltk
from nltk.corpus.reader.util import StreamBackedCorpusView 
import string 
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords = stopwords.words('english')


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pavanirajula/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
def get_valid_tokens(tokens: Union[List[str], StreamBackedCorpusView], remove_stopwords: bool=False) -> List[str]:
    """
    :param tokens: list of tokens that should be cleaned
    :param remove_stopwords: bool indicating if stopwords should be removed 
                             False by default
    :return: list of valid tokens
    """
    # your code here
    invalid_tokens = list(string.punctuation) + stopwords if remove_stopwords == True else []
    return [token.lower() for token in tokens if not token.isdigit() and token.lower() not in invalid_tokens]

In [333]:
# nltk.download("gutenberg")
# from nltk.corpus import gutenberg
# tokens = nltk.corpus.gutenberg.words('bible-kjv.txt')

# clean_words = get_valid_tokens(tokens,True)
# print(sorted(clean_words))


__b) Counting the surroundings (6 pts)__

In our simple model of word similarity we consider words as similar if they are being used in the same context (i.e. they have similar words surrounding them). 

Implement a function that, given a list of words, returns the count of all words in a designated word's surrounding. The context size indicates how many words to the left and right we consider, i.e. a context size of 1 indicates that we only consider the words immediately before and after a central word to be in its context. 

Your function should return a dictionary which maps each word $w$ from the input list to a dictionary. The inner dictionary should map each word that appears in the context of the central word $w$ to a number that indicates how often it appears in the context of $w$.

Make sure your implementation has linear complexity in the vocabulary / corpus length. Use the function signature specified in the cell below.

__Hint:__ Instead of the inner dictionary you can alternatively use `Counter` or `defaultdict` which can be found in the Python module `collections`. Moreover, consider the function ``ngrams`` from ``nltk``.

__Example:__ _For the input_
`['hi', 'james', 'how', 'are', 'you', 'hello', 'catherine', 'how', 'are', 'you']` _and_ `context_size=1`
_we wish to obtain:_
```
{'hi': {'james': 1},
 'james': {'hi': 1, 'how': 1},
 'how': {'james': 1, 'are': 2, 'catherine': 1},
 'are': {'how': 2, 'you': 2},
 'you': {'are': 2, 'hello': 1},
 'hello': {'you': 1, 'catherine': 1},
 'catherine': {'hello': 1, 'how': 1}}
```
__Explanation:__ _The word_ `hi` _is only surrounded by_ `james`_. The word_ `james` _is surrounded by_ `hi` _and_ `how` _. The word_ `how` _is surrounded by_ `james`_, by_ `catherine` _and by_ `are` _twice, ..._

_For_ `contextsize=2` _we obtain:_
```
{'hi': Counter({'james': 1, 'how': 1}),
'james': Counter({'hi': 1, 'how': 1, 'are': 1}),
'how': Counter({'are': 2, 'you': 2, 'hi': 1, 'james': 1, 'hello': 1, 'catherine': 1}),
'are': Counter({'how': 2, 'you': 2, 'james': 1, 'hello': 1, 'catherine': 1}),
'you': Counter({'how': 2, 'are': 2, 'hello': 1, 'catherine': 1}),
'hello': Counter({'are': 1, 'you': 1, 'catherine': 1, 'how': 1}),
'catherine': Counter({'you': 1, 'hello': 1, 'how': 1, 'are': 1})}
```

In [7]:
from collections import defaultdict
from typing import Counter


def get_surrounding_counts(tokens: Union[List[str], StreamBackedCorpusView], context_size: int) -> Dict[str, Dict[str, int]]:
    """
    :param tokens: list of tokens
    :param context_size: integer that indicates the number of context words that are considered on both sides of the central word
    :return: dict of dicts that holds the count of context words for each input token
    """
    # your code here
    surrounding_word_counter = {}
    for token in set(tokens):
        word_counter = Counter()
        indices = [i for i,word in enumerate(tokens) if word == token]
        for index in indices:
            for word in tokens[:index][-context_size:] + tokens[index+1:context_size+index+1]: 
                word_counter[word] += 1
        surrounding_word_counter[token] = word_counter
    return surrounding_word_counter

In [8]:
surround_words_counter = get_surrounding_counts(['hi', 'james', 'how', 'are', 'you', 'hello', 'catherine', 'how', 'are', 'you'],2)
# surround_words_counter = get_surrounding_counts(clean_words, 2)
print(surround_words_counter)

{'are': Counter({'how': 2, 'you': 2, 'james': 1, 'hello': 1, 'catherine': 1}), 'hello': Counter({'are': 1, 'you': 1, 'catherine': 1, 'how': 1}), 'how': Counter({'are': 2, 'you': 2, 'hi': 1, 'james': 1, 'hello': 1, 'catherine': 1}), 'catherine': Counter({'you': 1, 'hello': 1, 'how': 1, 'are': 1}), 'james': Counter({'hi': 1, 'how': 1, 'are': 1}), 'hi': Counter({'james': 1, 'how': 1}), 'you': Counter({'how': 2, 'are': 2, 'hello': 1, 'catherine': 1})}


__c) Keeping the top $k$ words in context (2 pts)__

To reduce the size of our result from task __b)__, we will only consider the most frequent context words for each token. Therefore, write a function that keeps only the $k$ most frequent words in the context of a designated word. Ties are resolved in lexicographic order (e.g. _**A**braham_ would be preferred to _**B**ethlehem_). The function should return a dictionary that maps each word in the outer dictionary to a __set__ of their top $k$ most frequent context words.

In [9]:
def to_sets(context_dict: Dict[str, Dict[str, int]], k: int) -> Dict[str, Set[str]]:
    """
    :param context_dict: dict of dicts that holds the count of context words for each word
    :param k: integer that specifies how many context words should be kept
    :return: dict that maps each word to a set of its k most frequent context words
    """
    # your code here
    for token in context_dict.keys():
        context_dict[token] = set([word[0] for word in context_dict[token].most_common(k)])
    return context_dict

In [10]:
topk_surround_words = to_sets(surround_words_counter, 1)
print(topk_surround_words)

{'are': {'how'}, 'hello': {'are'}, 'how': {'are'}, 'catherine': {'you'}, 'james': {'hi'}, 'hi': {'james'}, 'you': {'how'}}


__d) Finding the most similar words (4 pts)__

Given a dictionary as obtained in task __c)__ and a word $w$, we want to find the words that have the highest similarity to $w$ in terms of their context. We operationalize context similarity with the Jaccard index (https://en.wikipedia.org/wiki/Jaccard_index).
The Jaccard index of two sets $A$ and $B$ (in our case the sets of context words) is defined as:

$J(A, B) = \frac{|A \cap B|}{|A \cup B|}$

Write a function that returns the words that have the highest similarity to an input word $w$ (ignoring the input word itself). Since several words may have the same Jaccard similarity to the input word, your function should return the set of words that are most similar to $w$ and the respective value of the Jaccard similarity. Use the function signature specified in the cell below.

In [15]:
import math 
def find_most_similar_words(input_word: str, contexts: Dict[str, Set[str]]) -> (Set[str], float):
    """
    :param input_word: string that represents the word we are interested in
    :param contexts: dict that maps each word to a set of its most frequent context words
    :returns: 
        - set of the most similar words to the input word
        - float that indicates the highest Jaccard similarity to the input word
    """
    # your code here
    input_word_context = [word for word in contexts[input_word] if word != input_word]
    word_sim_scores = {}
    for word in input_word_context:
        set1 = set(input_word_context)
        set2 = set([word for word in contexts[word] if word != input_word])
        similarity = len(set(set1.intersection(set2)))/(len(set1.union(set2)))
        word_sim_scores[word] = similarity
    word_sim_scores = sorted(word_sim_scores.items(), key = lambda item:item[1], reverse=True)
    return set([word[0] for word in word_sim_scores if math.ceil(word[1]) == math.ceil(word_sim_scores[0][1])]), word_sim_scores[0][1]

In [16]:
find_most_similar_words('james', topk_surround_words)

({'hi'}, 0.0)

__e) Bringing it all together (3 pts)__

Finally, we want to apply our functions to the King James Bible (`'bible-kjv.txt'`) that is part of the ``gutenberg`` corpus. We intend to find the word that is most similar to ``god``. Follow the steps below:

i) Obtain a list of all tokens from the King James Bible and store it in a variable ``tokens``.  

ii) Clean the list of tokens with your function from __a)__ to get the list of valid tokens (without removing stopwords) and store it in a variable ``valid_tokens``.  

iii) Apply your function from __b)__ to count the context words for all valid tokens with a ``context_size`` of 2 and store the result in a variable ``context_counts``.  

iv) Using your function from __c)__, keep only the 20 most frequent words in a valid tokens context and store the result in a variable ``context_words``.  

v) Finally, find the most similar words to the word _god_ with your function from __d)__ and store the set of most similar words in the variable ``set_god`` and the highest Jaccard similarity in the variable ``sim_god``.  

In [17]:
# your code here
nltk.download("gutenberg")
from audioop import tostereo
from nltk.corpus import gutenberg
tokens = nltk.corpus.gutenberg.words('bible-kjv.txt')

valid_tokens = get_valid_tokens(tokens, True)
context_counts = get_surrounding_counts(valid_tokens,2)
context_words = to_sets(context_counts, 20)
set_god, sim_god = find_most_similar_words('god', context_words)
print(set_god, sim_god)


{'called', 'said', 'blessed', 'kind', 'saw', 'work', 'good', 'lord', 'created', 'heaven', 'firmament', 'every', 'man', 'light', 'made', 'waters', 'upon', 'earth', 'let', 'day'} 0.39285714285714285


[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/pavanirajula/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


### Task 3: Minimum cost string alignment (8 pts)

In this tak we want to compute an alignment between two strings, that has minimum edit distance. 

Implement a function that takes two strings and their edit distance matrix and returns a minimum cost alignment. You can assume that the edit distance matrix is provided by the function that you implemented in exercise 3, task 2, with a substitution cost of 2. 

A minimum cost alignment consists of two strings that, printed below each other comprise the alignment, where insertions and deletions are represented by a ``*``. Use the function signature in the cell below.

__Example:__ _Given the input strings_ ``"INTENTION"`` _and_ ``"EXECUTION"`` _and the corresponding edit distance matrix:_

``[[ 9  8  9 10 11 12 11 10  9  8]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 6  5  6  7  8  9  8  9 10 11]
 [ 5  4  5  6  7  8  9 10 11 10]
 [ 4  3  4  5  6  7  8  9 10  9]
 [ 3  4  5  6  7  8  7  8  9  8]
 [ 2  3  4  5  6  7  8  7  8  7]
 [ 1  2  3  4  5  6  7  6  7  8]
 [ 0  1  2  3  4  5  6  7  8  9]]``,
  
_your function should return the two strings_ ``INTE***NTION`` _and_ ``***EXECUTION`` _that represent the alignment, when printed below each other:_
 
 ``INTE***NTION``    
 ``***EXECUTION`` 


In [20]:
import numpy as np
from numpy.typing import NDArray

def get_alignment(str1: str, str2: str, D: NDArray[NDArray[int]]) -> (str, str): 
    '''
    :param str1: first string for alignment
    :param str2: second string for alignment
    :param D: edit distance matrix of str1 and str2
    :returns: tuple of strings that indicate the alignment of the input strings
    '''
    # your code here
    row, col = len(str1), len(str2)
    str1, str2 =  list(str1), list(str2)
    new_str1, new_str2 = [],[]

    while True:
#         print(D[row,col])
        cost = 0 if str1[row-1] == str2[col-1] else 2   
        if D[row,col] == D[row-1,col-1] + cost :
            new_str1, new_str2 = [str1[row-1]] + new_str1, [str2[col-1]] + new_str2
#             print(str1[row-1], str2[col-1])
            row, col = row - 1, col - 1
        else :
            if D[row,col] == D[row-1,col] + 1:
                new_str1, new_str2 = [str1[row-1]] + new_str1, ['*'] + new_str2
                row, col = row - 1, col
            elif D[row,col] == D[row,col-1] + 1:
                new_str1, new_str2 = ['*'] + new_str1, [str2[col-1]] + new_str2
                row, col = row, col - 1
#         print(row, col, new_str1, new_str2)
        if row == 0 and col == 0:
            return ''.join(new_str1), ''.join(new_str2)

In [21]:
min_edit_dist = [[ 9,  8,  9, 10, 11, 12, 11, 10,  9,  8],
 [ 8,  7,  8,  9, 10, 11, 10,  9,  8,  9],
 [ 7,  6,  7,  8,  9, 10,  9,  8,  9, 10],
 [ 6,  5,  6,  7,  8,  9,  8,  9, 10, 11],
 [ 5,  4,  5,  6,  7,  8,  9, 10, 11, 10],
 [ 4,  3,  4,  5,  6,  7,  8,  9, 10,  9],
 [ 3,  4,  5,  6,  7,  8,  7,  8,  9,  8],
 [ 2,  3,  4,  5,  6,  7,  8,  7,  8,  7],
 [ 1,  2,  3,  4,  5,  6,  7,  6,  7,  8],
 [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]]
min_edit_dist =np.rot90(np.transpose(np.asmatrix(min_edit_dist)))
print(min_edit_dist)
get_alignment("INTENTION","EXECUTION", min_edit_dist)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  6  7  8]
 [ 2  3  4  5  6  7  8  7  8  7]
 [ 3  4  5  6  7  8  7  8  9  8]
 [ 4  3  4  5  6  7  8  9 10  9]
 [ 5  4  5  6  7  8  9 10 11 10]
 [ 6  5  6  7  8  9  8  9 10 11]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 9  8  9 10 11 12 11 10  9  8]]


('INTE*NTION', '*EXECUTION')